global using IronType;
global using IronType.DependencyInjection;
global using IronType.EntityFramework.Relational;
global using IronType.Examples.BlazorWasm.Server.Data;
global using IronType.Examples.BlazorWasm.Shared;
global using IronType.NodaTime;
global using Microsoft.EntityFrameworkCore;
global using NodaTime;
global using System.Data;
